import React,{useEffect,useMemo,useRef,useState} from 'react'
import {ArrowLeft,BookOpen,CalendarDays,Check,ChevronDown,Plus,Trash2} from 'lucide-react'
import {AppState,makeId,STANDARD_MUSCLE_GROUPS} from '../lib/storage'
import Modal,{DialogActions,primaryButton} from '../components/Modal'

type Props={state:AppState;onSave:(state:AppState)=>void;templateDraftItems?:{name:string;description?:string}[]|null;templateDraftToken?:number;onTemplateDraftApplied?:()=>void}
type Tab='plan'|'library'
type Option={id:string;label:string;meta?:string}
const clone=(s:AppState):AppState=>JSON.parse(JSON.stringify(s))
const WEEKDAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
const asWeek=(source:AppState)=>{const s=clone(source);while(s.days.length<7){const i=s.days.length;s.days.push({id:makeId('day'),name:i===6?'Rest day':'Recovery',exerciseIds:[],isRestDay:true})}s.days=s.days.slice(0,7);return s}
const field='w-full rounded-xl border border-black/15 bg-white px-3 py-2.5 text-sm text-black outline-none transition focus:border-black focus:ring-2 focus:ring-black/5 dark:border-white/20 dark:bg-black dark:text-white dark:focus:border-white dark:focus:ring-white/10'
const homeExercise:Record<string,Partial<AppState['exercises'][number]>>={
  'Bodyweight squat':{sets:3,reps:'12–15',instructions:'Stand shoulder-width apart, sit your hips back and down, then drive through the whole foot.',commonMistakes:'Avoid knees collapsing inward, heels lifting, or rounding the lower back.'},
  'Push-up':{sets:3,reps:'8–15',instructions:'Keep a straight line from head to heels and lower your chest between your hands.',commonMistakes:'Avoid flared elbows, sagging hips, and shortening the range of motion.'},
  'Glute bridge':{sets:3,reps:'12–15',instructions:'Drive through your heels and squeeze your glutes at the top without arching your back.',commonMistakes:'Do not push through the toes or overextend the lower back.'},
  'Superman':{sets:3,reps:'10–12',instructions:'Lift arms and legs gently while keeping your neck neutral.',commonMistakes:'Avoid throwing the limbs upward or cranking the neck.'},
  'Mountain climbers':{tracking:'timed',sets:3,durationSeconds:30,instructions:'Hold a strong plank and alternate driving each knee toward your chest.',commonMistakes:'Avoid bouncing hips, collapsed shoulders, and sacrificing form for speed.'},
  'Forearm plank':{tracking:'timed',sets:3,durationSeconds:30,instructions:'Brace your trunk and maintain a straight line from head to heels.',commonMistakes:'Do not let the hips sag or rise, and avoid holding your breath.'},
  'Dead bug':{sets:3,reps:'8–10 / side',instructions:'Keep your lower back gently pressed down as opposite arm and leg extend.',commonMistakes:'Avoid arching the lower back or moving too quickly.'},
  'Jumping jacks':{tracking:'timed',sets:3,durationSeconds:30,instructions:'Land softly while moving arms and legs through a comfortable range.',commonMistakes:'Avoid locked knees, heavy landings, or shrugging the shoulders.'},
  'Reverse lunge':{sets:3,reps:'8–12 / side',instructions:'Step back, lower under control, then drive through the front foot.',commonMistakes:'Avoid the front knee collapsing inward or pushing off the rear foot.'},
  'Single-leg glute bridge':{sets:3,reps:'8–12 / side',instructions:'Keep hips level and extend them using the planted-side glute.',commonMistakes:'Avoid rotating the pelvis or driving through the lower back.'},
  'Calf raise':{sets:3,reps:'15–20',instructions:'Rise onto the ball of the foot, pause, and lower through the full range.',commonMistakes:'Avoid bouncing or rolling the ankles outward.'},
  'Wall sit':{tracking:'timed',sets:3,durationSeconds:30,instructions:'Keep your back against the wall with knees tracking over the feet.',commonMistakes:'Avoid placing hands on the thighs or letting knees cave inward.'}
}
const musclesByExercise:Record<string,string[]>={
  'Bench press':['Chest','Triceps','Shoulders'],'Incline dumbbell press':['Chest','Triceps','Shoulders'],'Shoulder press':['Shoulders','Triceps'],'Lateral raises':['Shoulders'],'Triceps pushdown':['Triceps'],
  'Pull-ups':['Back','Biceps'],'Lat pulldown':['Back','Biceps'],'Barbell row':['Back','Biceps'],'Face pull':['Shoulders','Back'],'Bicep curls':['Biceps'],
  'Squats':['Quadriceps','Glutes'],'Romanian deadlift':['Hamstrings','Glutes'],'Leg press':['Quadriceps','Glutes'],'Leg curls':['Hamstrings'],'Calf raises':['Calves'],
  'Incline press':['Chest','Shoulders','Triceps'],'Rows':['Back','Biceps'],'Pulldowns':['Back','Biceps'],'Overhead press':['Shoulders','Triceps'],'Curls':['Biceps'],'Skull crushers':['Triceps'],'Hammer curls':['Biceps','Forearms'],'Lunges':['Quadriceps','Glutes','Hamstrings'],'Hamstring curls':['Hamstrings'],'Calves':['Calves'],
  'Lat machine top':['Back','Biceps'],'Lat machine bottom':['Back','Biceps'],'Rowing':['Back','Biceps'],'One-arm rowing':['Back','Biceps'],'Bench flat':['Chest','Triceps'],'Bench incline':['Chest','Shoulders','Triceps'],'Bench decline':['Chest','Triceps'],'Flys':['Chest'],'Pushups':['Chest','Shoulders','Triceps'],'Hammer':['Biceps','Forearms'],'Barbell':['Biceps'],'Preacher':['Biceps'],'Press':['Shoulders','Triceps'],'Lateral':['Shoulders'],'Front':['Shoulders'],'Shrugs':['Shoulders','Back'],'Extensions':['Quadriceps'],
  'Bodyweight squat':['Quadriceps','Glutes'],'Push-up':['Chest','Shoulders','Triceps'],'Glute bridge':['Glutes','Hamstrings'],'Superman':['Lower Back','Glutes'],'Mountain climbers':['Abs','Shoulders'],'Forearm plank':['Abs','Lower Back'],'Dead bug':['Abs'],'Jumping jacks':['Quadriceps','Calves','Shoulders'],'Reverse lunge':['Quadriceps','Glutes','Hamstrings'],'Single-leg glute bridge':['Glutes','Hamstrings'],'Calf raise':['Calves'],'Wall sit':['Quadriceps','Glutes']
}

function MultiSelect({label,options,value,onChange}:{label:string;options:Option[];value:string[];onChange:(ids:string[])=>void}){
  const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null)
  useEffect(()=>{const close=(e:MouseEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
  const selected=options.filter(o=>value.includes(o.id))
  return <div ref={root} className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} className={`${field} flex min-h-[42px] items-center gap-2 text-left`}><span className={`min-w-0 flex-1 truncate ${selected.length?'':'text-black/40 dark:text-white/40'}`}>{selected.length===0?label:selected.length<=2?selected.map(x=>x.label).join(', '):`${selected.length} selected`}</span>{selected.length>0&&<span className="rounded-full bg-black px-2 py-0.5 text-[10px] font-bold text-white dark:bg-white dark:text-black">{selected.length}</span>}<ChevronDown size={15} className={`shrink-0 transition ${open?'rotate-180':''}`}/></button>{open&&<div className="absolute left-0 right-0 z-20 mt-1 max-h-60 overflow-y-auto rounded-xl border border-black/15 bg-white p-1.5 shadow-xl dark:border-white/20 dark:bg-neutral-950">{options.length?options.map(o=>{const checked=value.includes(o.id);return <button type="button" key={o.id} onClick={()=>onChange(checked?value.filter(id=>id!==o.id):[...value,o.id])} className="flex w-full items-center gap-3 rounded-lg px-2.5 py-2 text-left hover:bg-black/5 dark:hover:bg-white/10"><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-md border ${checked?'border-black bg-black text-white dark:border-white dark:bg-white dark:text-black':'border-black/20 dark:border-white/25'}`}>{checked&&<Check size={13}/>}</span><span className="min-w-0 flex-1 truncate text-sm font-medium">{o.label}</span>{o.meta&&<span className="text-[10px] text-black/40 dark:text-white/40">{o.meta}</span>}</button>}):<div className="px-3 py-5 text-center text-xs text-black/45 dark:text-white/45">Nothing available yet</div>}</div>}</div>
}

function NativeSelect({value,onChange,children}:{value:string;onChange:(value:string)=>void;children:React.ReactNode}){return <div className="relative"><select className={`${field} appearance-none pr-9`} value={value} onChange={e=>onChange(e.target.value)}>{children}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-black/45 dark:text-white/45"/></div>}

export default function QueueEditor({state,onSave,templateDraftItems,templateDraftToken,onTemplateDraftApplied}:Props){
  const [tab,setTab]=useState<Tab>('plan'),[draft,setDraft]=useState(()=>asWeek(state)),[expanded,setExpanded]=useState<string|null>(null)
  const [validationMessage,setValidationMessage]=useState('')
  useEffect(()=>setDraft(asWeek(state)),[state])
  useEffect(()=>{
    if(!templateDraftItems?.length)return
    const next:AppState={exercises:[],muscleGroups:STANDARD_MUSCLE_GROUPS.map(group=>({...group,exerciseIds:[]})),days:[],history:clone(state).history,weightTracking:clone(state).weightTracking,weeklyWorkoutGoal:state.weeklyWorkoutGoal,restSeconds:state.restSeconds,restTimerSound:state.restTimerSound,restTimerVibration:state.restTimerVibration,reminders:clone(state).reminders}
    const ensureGroup=(name:string)=>{let group=next.muscleGroups.find(g=>g.name===name);if(!group){group={id:makeId('group'),name,exerciseIds:[]};next.muscleGroups.push(group)}return group}
    templateDraftItems.forEach(item=>{
      if(item.description==='__REST__'){next.days.push({id:makeId('day'),name:item.name,exerciseIds:[],isRestDay:true});return}
      const dayExerciseIds:string[]=[]
      ;(item.description||'').split('\n').map(x=>x.trim()).filter(Boolean).forEach(name=>{
        const muscleNames=musclesByExercise[name]||['Full Body']
        const groupIds=muscleNames.map(muscle=>ensureGroup(muscle).id)
        let exercise=next.exercises.find(ex=>ex.name===name)
        if(!exercise){const preset=homeExercise[name]||{};exercise={id:makeId('ex'),name,tracking:preset.tracking||'reps',sets:preset.sets||3,reps:preset.reps||'8–12',muscleGroupIds:groupIds,...preset};next.exercises.push(exercise)}
        if(!dayExerciseIds.includes(exercise.id))dayExerciseIds.push(exercise.id)
        exercise.muscleGroupIds=[...new Set([...(exercise.muscleGroupIds||[]),...groupIds])]
        groupIds.forEach(groupId=>{const group=next.muscleGroups.find(g=>g.id===groupId)!;if(!group.exerciseIds.includes(exercise!.id))group.exerciseIds.push(exercise!.id)})
      })
      next.days.push({id:makeId('day'),name:item.name,exerciseIds:dayExerciseIds})
    })
    setDraft(next);setTab('plan');setExpanded(null);onTemplateDraftApplied?.()
  },[templateDraftToken])
  const dirty=useMemo(()=>JSON.stringify(draft)!==JSON.stringify(state),[draft,state])
  const update=(fn:(s:AppState)=>void)=>setDraft(old=>{const next=clone(old);fn(next);return next})
  const groupOptions=draft.muscleGroups.map(x=>({id:x.id,label:x.name||'Untitled group',meta:`${x.exerciseIds.length} exercises`}))
  const exerciseOptions=draft.exercises.map(x=>({id:x.id,label:x.name||'Untitled exercise',meta:x.tracking==='timed'?`${x.durationSeconds||30}s × ${x.sets||3}`:`${x.sets||3} × ${x.reps||'8–12'}`}))
  const removeExercise=(id:string)=>update(s=>{s.exercises=s.exercises.filter(x=>x.id!==id);s.days.forEach(d=>d.exerciseIds=d.exerciseIds.filter(x=>x!==id));s.muscleGroups.forEach(g=>g.exerciseIds=g.exerciseIds.filter(x=>x!==id))})
  const tabs=[{id:'plan' as const,label:'Workout Plan',Icon:CalendarDays,count:draft.days.length},{id:'library' as const,label:'Exercise Library',Icon:BookOpen,count:draft.exercises.length}]
  const addExercise=()=>{const id=makeId('ex');update(s=>s.exercises.push({id,name:'',tracking:'reps',sets:3,reps:'8–12'}));setExpanded(id)}
  const editingExercise=tab==='library'?draft.exercises.find(ex=>ex.id===expanded):undefined
  const saveDraft=()=>{
    const incomplete=draft.exercises.find(ex=>!ex.name.trim()||!(ex.muscleGroupIds?.length||draft.muscleGroups.some(g=>g.exerciseIds.includes(ex.id))))
    if(incomplete){setTab('library');setExpanded(incomplete.id);setValidationMessage('Add a name and at least one muscle group to every exercise before saving.');return}
    if(!draft.days.length){setValidationMessage('Add at least one training day before saving.');return}
    onSave(draft)
  }

  return <div className="mb-28">
    <Modal open={Boolean(validationMessage)} title="Program needs attention" description={validationMessage} onClose={()=>setValidationMessage('')}><DialogActions><button className={primaryButton} onClick={()=>setValidationMessage('')}>Review program</button></DialogActions></Modal>
    {!editingExercise&&<nav className="grid grid-cols-2 gap-1 rounded-2xl border border-black/10 bg-black/[.03] p-1 dark:border-white/10 dark:bg-white/[.06]">{tabs.map(({id,label,Icon,count})=><button key={id} onClick={()=>{setTab(id);setExpanded(null)}} className={`rounded-xl px-2 py-2.5 transition ${tab===id?'bg-white text-black shadow-sm dark:bg-white dark:text-black':'text-black/45 dark:text-white/45'}`}><span className="flex items-center justify-center gap-1.5 text-xs font-semibold"><Icon size={14}/>{label}<span className="font-normal opacity-50">{count}</span></span></button>)}</nav>}
    <div className="mt-4 space-y-2">
      {tab==='plan'&&draft.days.map((day,i)=><EditorCard key={day.id} open={expanded===day.id} onToggle={()=>setExpanded(expanded===day.id?null:day.id)} title={day.name} titlePlaceholder={day.isRestDay?'Recovery':'Push day'} onTitleChange={name=>update(s=>{const x=s.days.find(x=>x.id===day.id);if(x)x.name=name})} eyebrow={WEEKDAYS[i%7]} summary={day.isRestDay?'Rest':`${day.exerciseIds.length} exercises`}>
        <L>Day type</L><NativeSelect value={day.isRestDay?'rest':'training'} onChange={value=>update(s=>{const x=s.days.find(x=>x.id===day.id);if(x){x.isRestDay=value==='rest';if(x.isRestDay)x.exerciseIds=[]}})}><option value="training">Training day</option><option value="rest">Rest / recovery day</option></NativeSelect>
        {!day.isRestDay&&<><L>Exercises</L><MultiSelect label={exerciseOptions.length?'Choose exercises':'Add exercises in the library first'} options={exerciseOptions} value={day.exerciseIds} onChange={ids=>update(s=>{const x=s.days.find(x=>x.id===day.id);if(x)x.exerciseIds=ids})}/></>}
      </EditorCard>)}
      {tab==='library'&&!editingExercise&&draft.exercises.map(ex=><button type="button" key={ex.id} onClick={()=>setExpanded(ex.id)} className="flex w-full items-center gap-3 rounded-2xl border border-black/10 p-4 text-left transition hover:border-black/25 dark:border-white/15 dark:hover:border-white/30"><div className="min-w-0 flex-1"><div className="truncate font-semibold">{ex.name||'Untitled exercise'}</div><div className="mt-1 text-xs text-black/45 dark:text-white/45">{ex.tracking==='timed'?`${ex.durationSeconds||30} seconds × ${ex.sets||3} sets`:`${ex.sets||3} sets × ${ex.reps||'8–12'} reps`}</div></div><ChevronDown size={17} className="-rotate-90 text-black/35 dark:text-white/35"/></button>)}
      {editingExercise&&<section>
        <header className="mb-5 flex items-center justify-between"><button type="button" onClick={()=>setExpanded(null)} className="flex items-center gap-1.5 text-sm font-semibold"><ArrowLeft size={17}/>Library</button><button type="button" onClick={()=>setExpanded(null)} className="rounded-xl bg-black px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-black">Done</button></header>
        <input aria-label="Exercise name" className="w-full border-0 border-b border-black/15 bg-transparent pb-2 text-2xl font-bold outline-none placeholder:text-black/30 focus:border-black dark:border-white/20 dark:placeholder:text-white/30 dark:focus:border-white" value={editingExercise.name} placeholder="New exercise" onChange={e=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.name=e.target.value})}/>
        <L>Muscle groups</L><MultiSelect label="Choose at least one" options={groupOptions} value={editingExercise.muscleGroupIds||draft.muscleGroups.filter(g=>g.exerciseIds.includes(editingExercise.id)).map(g=>g.id)} onChange={ids=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.muscleGroupIds=ids;s.muscleGroups.forEach(g=>g.exerciseIds=ids.includes(g.id)?[...new Set([...g.exerciseIds,editingExercise.id])]:g.exerciseIds.filter(id=>id!==editingExercise.id))})}/>
        <L>Tracking</L><div className="grid grid-cols-2 gap-1 rounded-xl bg-black/[.05] p-1 dark:bg-white/[.08]">{(['reps','timed'] as const).map(mode=><button type="button" key={mode} onClick={()=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.tracking=mode})} className={`rounded-lg px-3 py-2 text-sm font-semibold transition ${(editingExercise.tracking||'reps')===mode?'bg-white shadow-sm dark:bg-white dark:text-black':'text-black/45 dark:text-white/45'}`}>{mode==='reps'?'Reps':'Timed'}</button>)}</div>
        <div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-end gap-3"><div><L>Sets</L><input className={field} type="number" min="1" value={editingExercise.sets||''} onChange={e=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.sets=Number(e.target.value)||undefined})}/></div><span className="pb-3 text-sm text-black/35 dark:text-white/35">×</span><div><L>{editingExercise.tracking==='timed'?'Seconds':'Reps'}</L><input className={field} type={editingExercise.tracking==='timed'?'number':'text'} min="1" value={editingExercise.tracking==='timed'?editingExercise.durationSeconds||'':editingExercise.reps||''} placeholder={editingExercise.tracking==='timed'?'30':'8–12'} onChange={e=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(!x)return;if(x.tracking==='timed')x.durationSeconds=Number(e.target.value)||undefined;else x.reps=e.target.value})}/></div></div>
        <L>Instructions</L><textarea className={`${field} min-h-24 resize-y`} value={editingExercise.instructions||''} placeholder="Setup, movement and useful cues…" onChange={e=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.instructions=e.target.value})}/>
        <details className="mt-5 rounded-xl border border-black/10 p-3 dark:border-white/15"><summary className="cursor-pointer text-sm font-semibold text-black/60 dark:text-white/60">Optional details</summary><L>Common mistakes</L><textarea className={`${field} min-h-20 resize-y`} value={editingExercise.commonMistakes||''} placeholder="What should someone avoid doing?" onChange={e=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.commonMistakes=e.target.value})}/><L>Equipment</L><input className={field} value={editingExercise.equipment||''} placeholder="e.g. Barbell" onChange={e=>update(s=>{const x=s.exercises.find(x=>x.id===editingExercise.id);if(x)x.equipment=e.target.value})}/></details>
        <button type="button" onClick={()=>{removeExercise(editingExercise.id);setExpanded(null)}} className="mt-6 flex items-center gap-1.5 text-xs text-red-600 dark:text-red-400"><Trash2 size={14}/>Delete exercise</button>
      </section>}
      {(tab==='plan'?draft.days:draft.exercises).length===0&&<div className="rounded-2xl border border-dashed border-black/20 px-5 py-10 text-center dark:border-white/20"><div className="text-sm font-semibold">Nothing here yet</div><div className="mt-1 text-xs text-black/45 dark:text-white/45">Add an exercise to get started.</div></div>}
    </div>
    {tab==='library'&&!editingExercise&&<button onClick={addExercise} className="mt-3 flex w-full items-center justify-center gap-1.5 rounded-xl bg-black px-3 py-3 text-sm font-semibold text-white dark:bg-white dark:text-black"><Plus size={16}/>Add exercise</button>}
    {dirty&&<div className="fixed bottom-0 left-1/2 z-30 flex w-full max-w-md -translate-x-1/2 gap-2 border-t border-black/10 bg-white/95 p-3 pb-[max(12px,env(safe-area-inset-bottom))] backdrop-blur dark:border-white/15 dark:bg-black/95"><button className="flex-1 rounded-xl border border-black/15 py-3 text-sm font-semibold dark:border-white/20" onClick={()=>{setDraft(clone(state));setExpanded(null)}}>Discard</button><button className="flex-[1.4] rounded-xl bg-black py-3 text-sm font-semibold text-white dark:bg-white dark:text-black" onClick={saveDraft}>Save program</button></div>}
  </div>
}

function L({children}:{children:React.ReactNode}){return <label className="mb-1 mt-3 block text-[10px] font-semibold uppercase tracking-wider text-black/45 dark:text-white/45">{children}</label>}
function EditorCard({open,onToggle,title,titlePlaceholder,eyebrow,summary,onTitleChange,onDelete,children}:{open:boolean;onToggle:()=>void;title:string;titlePlaceholder?:string;eyebrow:string;summary:string;onTitleChange?:(title:string)=>void;onDelete?:()=>void;children:React.ReactNode}){return <section className={`overflow-visible rounded-2xl border transition ${open?'border-black/30 bg-black/[.015] dark:border-white/35 dark:bg-white/[.04]':'border-black/10 dark:border-white/15'}`}><div className="flex items-center gap-3 p-3.5 text-left"><div className="min-w-0 flex-1"><div className="text-[9px] font-semibold uppercase tracking-widest text-black/40 dark:text-white/40">{eyebrow}</div>{open&&onTitleChange?<input aria-label={`${eyebrow} name`} className="mt-0.5 w-full border-0 border-b border-black/15 bg-transparent pb-1 font-semibold outline-none placeholder:text-black/30 focus:border-black dark:border-white/20 dark:placeholder:text-white/30 dark:focus:border-white" value={title} placeholder={titlePlaceholder||'Untitled'} onChange={e=>onTitleChange(e.target.value)}/>:<button type="button" onClick={onToggle} className="mt-0.5 block w-full truncate text-left font-semibold">{title||'Untitled'}</button>}</div><span className="text-xs text-black/40 dark:text-white/40">{summary}</span><button type="button" onClick={onToggle} aria-label={open?'Collapse':'Expand'}><ChevronDown size={17} className={`transition ${open?'rotate-180':''}`}/></button></div>{open&&<div className="border-t border-black/10 p-3.5 pt-1 dark:border-white/10">{children}{onDelete&&<button type="button" onClick={onDelete} className="mt-4 flex items-center gap-1.5 text-xs text-red-600 dark:text-red-400"><Trash2 size={14}/>Delete</button>}</div>}</section>}
